### ISSUE TITLE
Todo List Janvier

### ISSUE THREAD

**Issue by EtienneSchmitz** [NAELIC/todolist#1]
# TodoList

## Général 

- [x] Site web pour garder une trace de la mécanique (Conception, fonctionnalité, ...)
- [x] Chercher Alternative Trello => Github

- - -

## Serveur (Reporté à Février)

- [ ] Mise en place LDAP
- [ ] Achat serveur, NDD (28 janvier)
- [ ] Mise en place nextcloud (31 janvier)
- [ ] Mise en place wiki Bookstack (28 janvier)
- [ ] Mise en place verdaccio (28 janver)
- [ ] Utiliser diun (https://crazymax.dev/diun/)
- [ ] Github pipeline for publish package (31 janvier)

- - -

### General
- [x] Enum Kick
- [ ] Supress warning (Remove some rules in eslint)
- [x] Rename all I*** Interface to Abstract***

### Librairie

- [x] Ajouter des tests dans la librairie Maths
- [x] Maths : Remove default export
- [x] Types : Convention for internal (*Message + I for interface) 
- [ ] Rename league to network
- [x] Types : Ou mettre la couleur

### Viewer

- [x] Finir d'afficher le terrain viewer
- [ ] Ajouter sous forme d'electron (avec un plugin de mise à jour)
- [ ] Plugin courbe

### Manager IA

- [ ] Créer un manager IA
- [ ] Lancer une intégration avec GameController
- [ ] Lancer deux IA - deux équipes sur le même ordinateur

### Data

- [ ] Ajout de certains filtres : Filtres de supression, filtre de changement de côté
- [ ] Améliorer pipeline de filtres
- [ ] Constante
- [ ] Ajouter l'informations de la vitesse et de l'accélération
- [x] Rename data to world 
- [ ] Remettre les status

### Bots

- [x] Refacto 

### Control

- [ ] Refacto MoveTo

- - -

## Candidature 

- [ ] Faire le A*
- [ ] Mise en place scénario de la vidéo
- [x] Préparer le template overleaf (tdp namec 2020) 
- [x] Envoyer lien overleaf (partage)

- - -

## Médiation

- [ ] Préparer le sujet 

- - -

## Simulateur

- [x] Publier en public
- [x] Régler le soucis des fps
- [x]  Merge la PR sur le dead code
- [x]  Docker
- [ ] Splitter les classes
- [ ] Enlever les pointeurs
- [ ] Enlever les warnings

- - -
## Documentation 

- [ ] Procédure Installation (Windows, Mac, Linux)
- [ ] Présentation nouveaux services
- [ ] Convention de nommage

**Comment by EtienneSchmitz** [comment]
# Activités 21 janvier 2020

## Présentation de NAELIC

__Pôle concernés :__ Tous (Louis D.)

__Nombre d'étudiants :__ 1+

__Résultat attendu :__ Texte en anglais entre dix et quinze lignes.

__Présentation de l'activité :__ 
L'introduction du TDP doit présenter l'équipe de sa création à aujourd'hui. Dans le cadre de cette activité vous ferez cette présentation. Il est à noter que le texte doit être fait en Anglais.

## Ecriture des site maintenances

__Pôle concernés :__ Tous (axé sur Fabrication)

__Nombre d'étudiants :__ 1+ (Gurvan)

__Résultat attendu :__ Document mettant en lien les idées proposés.

__Présentation de l'activité :__ 
Dans le but de partager les robots entre nous, il faut garder un historique des modifications, des pannes du robots, ainsi que des check-ups réguliers fait par le pôle Mécanique (Maintenance, Fabrication).
Il vous est demandé de rédiger les premières lignes de l'ensemble des fonctionnalités.

## Ecriture du scénario de la vidéo de présentation.

__Pôle concernés :__ Software

__Nombre d'étudiants :__ 1+ (Aurélien)

__Résultat attendu :__ Document présentant un scénario.

__Présentation de l'activité :__ 
Dans le but de candidater, nous devons faire une vidéo.
La partie Software doit pouvoir écrire un scénario avec les capacités actuelles (en ajoutant l'algorithme A*).

## Ecriture du texte pour la partie Système embarqué.

__Pôle concernés :__ Software

__Nombre d'étudiants :__ 1+ (Jade & Gurvan)

__Résultat attendu :__ Texte en anglais présentant les améliorations

__Présentation de l'activité :__ 

## Ecriture du texte pour la partie Software.

__Pôle concernés :__ Software 

__Nombre d'étudiants :__ 1 (Baptiste, Thibault)

__Résultat attendu :__ Texte en anglais présentant les améliorations

__Présentation de l'activité :__
