### ISSUE TITLE
Todo List - Février

### ISSUE THREAD

**Issue by EtienneSchmitz** [NAELIC/todolist#3]
# TodoList

### Serveur

- [ ] Mise en place LDAP
- [ ] Achat serveur, NDD
- [ ] Mise en place nextcloud
- [ ] Mise en place wiki Bookstack
- [ ] Mise en place verdaccio
- [ ] Utiliser diun (https://crazymax.dev/diun/)
- [ ] Github pipeline for publish package 

- - -

### General

- [x]  Supress warning (Remove some rules in eslint)
- [x] Rename league to network

### Viewer

- [ ] Ajouter sous forme d'electron (avec un plugin de mise à jour)
- [ ] Plugin courbe

### Data

- [ ] Ajout filtre de changement
- [ ] Ajout filtre de supression
- [x] Améliorer pipeline de filtres
- [ ] Constante
- [ ] Ajouter l'informations de la vitesse et de l'accélération
- [x] Remettre les status (In Progress)

### Control 

- [ ] Refacto MoveTo
- [ ] Ajouter MoveBy

### Bots

- [x] Refacto 

### Maths

- [ ] https://github.com/NAELIC/nodetron-math/issues/8
- [ ] https://github.com/NAELIC/nodetron-math/issues/7
- [x] https://github.com/NAELIC/nodetron-math/issues/6
- [ ] https://github.com/NAELIC/nodetron-math/issues/3

### Util 
- [ ] https://github.com/NAELIC/nodetron-util/issues/1
- [ ] Documenter le code

### Types
- [ ] Documenter le code

### Manager IA

- [ ] Créer un manager IA
- [x] Lancer une intégration avec GameController
- [x] Lancer deux IA - deux équipes sur le même ordinateur

- - -

## Documentation 

- [ ] Procédure Installation (Windows, Mac, Linux)
- [ ] Présentation nouveaux services
- [ ] Convention de nommage
